CREATE TABLE USERS(
ID INT(50) NOT NULL,
USERNAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PSW VARCHAR(100) NOT NULL,
API VARCHAR(100) NOT NULL,
PRIMARY KEY(ID)
);
CREATE TABLE CHANNEL(
id INT auto_increment,
DT VARCHAR(20),
TEMP VARCHAR(20) ,
HUMI varchar(20) ,
SOIL VARCHAR(20),
FLOW VARCHAR(20),
IDCHANNEL INT(30) NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(IDCHANNEL) REFERENCES USERS(ID)
);
CREATE TABLE LED(
id INT auto_increment,
LIGHT VARCHAR(5),
IDCONTROL INT(30) NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(IDCONTROL) REFERENCES USERS(ID)
);
CREATE TABLE HUMI(
id INT auto_increment,
HUMIDIFIER VARCHAR(5),
IDCONTROL INT(30) NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(IDCONTROL) REFERENCES USERS(ID)
);
CREATE TABLE PUMPS(
id INT auto_increment,
PUMP VARCHAR(5),
IDCONTROL INT(30) NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(IDCONTROL) REFERENCES USERS(ID)
);
CREATE TABLE WATERS(
id INT auto_increment,
WATER VARCHAR(5),
IDCONTROL INT(30) NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY(IDCONTROL) REFERENCES USERS(ID)
)